### PR TITLE
feat(config): add additional configuration formats

### PR DESCRIPTION
**Pull request by EpicGamer007**
At the moment, for configuration, you need to create a `.replapirc.json` file. However, what if there is some point in the future where it is necessary to use a .env variable? This can be solved with creating a `.js`/`.mjs`  config file. This is exactly what I did. I added en else if in constants.js and `constants.mjs` which allows for a `.replapirc.js` and `.replapirc.mjs` respectively. I have tested it and it seems to work fine. However, i did not use the `npm run build:cjs` command (or something like that) for the common js version because it would import so much extra junk for async/await. I did that manually. If you can check it out, that would be great.

### CODE REVIEW

**Review by RayhanADev — CHANGES_REQUESTED** [review]
Hiya! ✨ Awesome ✨ first contribution :D.

A few changes I would love to see with your system before merging:
- Typically the naming convention for `*.*js` files is `package-name.config.*js`. That little change would make things splendid!
- The way that I create config files is at #esm/index.mjs:38 and #esm/index.mjs:44. The program automatically creates that `replapirc.json` file when it starts (the ReplAPI function you import). Perhaps do something that allows the user to change what file format that their config is in (i.e an option passed in after config variables and it would output a replapirc.json, replapi.config.js, replapi.config.cjs, or replapi.config.mjs). Here's an example:
  ```js
  import ReplAPI from 'replapi-it';
  const replapi = ReplAPI({
    username: 'RayhanADev',
  }, '.mjs'); // config file type is second parameter
  ```
- On #esm/src/utils/constants.mjs:9 I see that you look for replapirc.mjs, however not it's similar files (.cjs, .js). You should probably add support for those as well

And then just a few meta changes:
- Are you using eslint (`npm run lint:fix`) and prettier (`npm run format:fix`)? I think you are but I'm just making sure.
- Be sure to run the CommonJS build (`npm run build:cjs`). I understand why you might dislike the junk wrappers, but you don't really need to care about them, that's just Babel making sure everything works the same in CommonJS and it is important that you run the build instead of manually editing the CommonJS build. The work that you need to do is all in the ESM files.
- We use [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) for our commit conventions. If you could please follow this as well, it helps keep the repository organized!

Again, thanks for the awesome PR, I truthfully never would have thought of this. It's brilliant!

**Comment by EpicGamer007** [comment]
Ok, I will take a look today. I did run the linter and prettier so don't worry about that though. I will take a look at the changes you requested later.

**Comment by EpicGamer007** [comment]
Also, I am not sure how I would be able to use .mjs files in the .js version and .js and .cjs files in the ESM version, any ideas?

**Comment by RayhanADev** [comment]
> Also, I am not sure how I would be able to use .mjs files in the .js version and .js and .cjs files in the ESM version, any ideas?

I'm sorry could you elaborate, I'm not quite getting it...

**Comment by EpicGamer007** [comment]
Like, at the moment, for the .mjs version, i use the `import()` function to import. However, in .mjs files, there is no `require()`, so how will I be able to accept common js modules if there is no require?

**Comment by RayhanADev** [comment]
@EpicGamer007 I see what you mean, however you should be able to (please, correct me if I'm wrong) simply `import` CommonJS modules.

This might help you out a bit: https://blog.logrocket.com/how-to-use-ecmascript-modules-with-node-js/

[Eslint has one of the easier examples](https://github.com/eslint/eslint/blob/master/lib/init/config-file.js) of creating config files, and if read/writing config files is getting hefty in index and constants then feel free to move it over to a new file in `./.scripts/config-file.js`. I hope this helps you out :D.

**Comment by EpicGamer007** [comment]
ah ok, i will try it out later. i didnt know import works with commonjs

**Comment by EpicGamer007** [comment]
@RayhanADev , should the config files be named `replapiit.config.js` or `replapi.config.js`?

**Comment by RayhanADev** [comment]
@EpicGamer007 prob `replapi.config.*js` to match the `*rc.json` naming convention as well.

**Review by RayhanADev — COMMENTED** [review]
Woof, looking really good!

**Comment by EpicGamer007** [comment]
@RayhanADev , no it isnt working. The problem is that you made your constants.js with readFileSync so I have to promisify everything for it to work. this means promisifying all the classes too :'(

**Comment by RayhanADev** [comment]
@EpicGamer007 wait why do you need to promisify? Just use readFileSync?

Also if you wouldn't mind could you send me a link the Repl?

**Comment by EpicGamer007** [comment]
Sure, i can send join link. Also, i pulled back the changes i made to the point where it was working kind of ok. I will put explanation there: || https://replit.com/join/kheypkjg-epicgamer007 || <-- here is the link. tell me when you have used it so i can generate a new one

**Comment by EpicGamer007** [comment]
@RayhanADev can you get on the repl right now? I need some help with fixing it..

**Comment by RayhanADev** [comment]
@EpicGamer007 I'll try, but I'm out right now

**Comment by EpicGamer007** [comment]
@RayhanADev, the current problem is that right now, for the ESM version to work, I am using top level await, which is available with EcmaScript modules. However, whenever I try to use Babel to convert that top level await to commonjs, it is saying "unexpected keyword await" or something like that because there is no async function wrapping it. And we can't wrap it in an async function because then there would be no way to export it so I have run into a dillema

**Comment by RayhanADev** [comment]
@EpicGamer007 I can get on for a few right now

**Comment by EpicGamer007** [comment]
i see you are online right now, i can too (i am on the repl rn)

**Comment by RayhanADev** [comment]
@EpicGamer007 if you get a moment, do you want to work on a `.mjs` loader for the cosmiconfig reader? I'm available pretty much anytime today.

**Comment by EpicGamer007** [comment]
@RayhanADev , I have a test for an outside school class until 12:15 pm pst. i can get on after that. (2:15 - 2:20 pst for you)

**Comment by RayhanADev** [comment]
Okay sure

**Comment by EpicGamer007** [comment]
@RayhanADev , I am on now

**Review by RayhanADev — APPROVED** [review]
Looks good to me, if there's nothing else you want to add I'm ready to merge this to the main :).

**Comment by EpicGamer007** [comment]
nice i will check it out then ping you once I am ready. Just want to make a few last minute changes maybe (not related to the config files)

**Comment by EpicGamer007** [comment]
@RayhanADev , I updated the gitignore (to include the new config files), feel free to review and merge now

**Review by RayhanADev — APPROVED** [review]

**Comment by RayhanADev** [comment]
@EpicGamer007 tada 🎉

**Pull request merged**
